### ISSUE TITLE
Constraint Validations having issues with threading

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#1065]
When a validator shares its StructureDefinitions through a resource resolver (such as a CachedResourceResolver) the validator adds in an annotation of the compiled fhirpath expression.
This manipulation of the annotation is not thread safe, so instead we can put a lock on the outside while putting the annotation in.
https://github.com/FirelyTeam/fhir-net-api/blob/8deb078eee04e3ed8c0e34074bad4144fa4b5ee8/src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs#L106
Also, this code should probably be SetAnnotation, not AddAnnotation as don't really want to put in multiple values for this annotation.

**Comment by brianpos** [comment]
I've made this change in my fork to handle this in my server.
https://github.com/brianpos/fhir-net-api/commit/2c0a34c7cd0db328883ff1d64d39319985c79cf3

**Comment by ewoutkramer** [comment]
Yes, we should add something along those lines!

**Comment by cknaap** [comment]
Vonk recently failed a unittest and the cause is probably similar: concurrent access to Annotations.

Exception: `System.IndexOutOfRangeException : Index was outside the bounds of the array.`

Partial Stacktrace:
```
   at System.Collections.Generic.LargeArrayBuilder`1.Add(T item)
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Hl7.Fhir.Utility.ObjectListExtensions.RemoveOfType(IList`1 me, Type t) in d:\a\1\s\common\src\Hl7.Fhir.Support\Utility\ObjectList.cs:line 27
   at Hl7.Fhir.Utility.AnnotatableExtensions.SetAnnotation[A](IAnnotatable annotatable, A annotation) in d:\a\1\s\common\src\Hl7.Fhir.Support\Utility\IAnnotatable.cs:line 30
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.getSnapshotRootElement(StructureDefinition sd, String profileUri, String location) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 1981
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.createNewElement(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 661
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.merge(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 610
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.mergeElement(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 821
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.createNewElement(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 703
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.merge(ElementDefinitionNavigator snap, ElementDefinitionNavigator diff) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 610
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.generate(StructureDefinition structure) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 396
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.ensureSnapshot(StructureDefinition sd, String profileUri, String location) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 1794
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.generate(StructureDefinition structure) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 255
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.ensureSnapshot(StructureDefinition sd, String profileUri, String location) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 1794
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.generate(StructureDefinition structure) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 255
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.Generate(StructureDefinition structure) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 157
   at Hl7.Fhir.Specification.Snapshot.SnapshotGenerator.Update(StructureDefinition structure) in d:\a\1\s\src\Hl7.Fhir.Specification\Specification\Snapshot\SnapshotGenerator.cs:line 125
   at Vonk.Fhir.R3.Common.ConformanceCacheR3.CompleteStructureDefinitionSnapshot(Resource resource, CacheCollection`1 cache) in C:\agent\_work\2\s\src\Vonk.Fhir.R3\Common\ConformanceCacheR3.cs:line 71
```

**Comment by cknaap** [comment]
I would favor a solution based on a Concurrent collection to avoid locks as much as possible.
