### ISSUE TITLE
Vonkloader bundle upload causes System.AggregateException

### ISSUE THREAD

**Issue by dattachandan** [FirelyTeam/fhir-net-api#1243]
Hi team

I follow the readme instructions from the vonkoader [tool](http://docs.simplifier.net/vonkloader/).  Are there some zip samples that works as shown in the devdays [demo](https://www.devdays.com/wp-content/uploads/2019/12/Vadim-Peretokin-Firely-tooling-for-FHIR-DevDays-2019-Redmond.pdf)?

While trying to upload a single large bundle zip to the vonk server using vonkloader tool, I am getting this error below - where can I find the cause? This is because there are no logs on the vonk server

```
vonkloader -file:C:\work\fhir-pd\src\firely-vonk\fhir-vonk-mongodb-tests\bundle-1580335003480-5k.zip   -server:http://localhost:8080

Log is written to C:\Users\chandan\AppData\Local\Temp\VonkLoader2020-02-04_131519.log
2020-02-04 13:15:19 [Information] Trying to read examples from file C:\work\fhir-pd\src\firely-vonk\fhir-vonk-mongodb-tests\bundle-1580335003480-5k.zip
2020-02-04 13:15:19 [Information] Sending examples to FHIR server at http://localhost:8080/
2020-02-04 13:15:19 [Information] Limit not specified, loading all examples in the file.
2020-02-04 13:15:19 [Information] Limiting number of parallel requests to 50
2020-02-04 13:15:19 [Information] Testing Server http://localhost:8080/: Retrieving its CapabilityStatement.
2020-02-04 13:15:19 [Information] Testing Server http://localhost:8080/: CapabilityStatement successfully retrieved.
2020-02-04 13:15:20 [Information] Sending request PUT http://localhost:8080/Bundle/1
2020-02-04 13:18:20 [Error] "bundle-1580335003480-5k.xml": task was canceled. Status: Canceled
2020-02-04 13:18:20 [Error] "bundle-1580335003480-5k.xml": failed with exception
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at VonkLoader.Loader.SendRequest(RequestInfo request, String serverAddress, CancellationTokenSource cts) in C:\agent\_work\6\s\src\VonkLoader\Loader.cs:line 104
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```

**Comment by mbaltus** [comment]
You can check the log file (C:\Users\chandan\AppData\Local\Temp\VonkLoader2020-02-04_131519.log) to see if there's more information about what went wrong. Also, please check your Vonk logs to see if the request was received and if there's more information about the handling of the request.
Please email us at Vonk (see our [contact page](http://docs.simplifier.net/vonk/contact.html)) to discuss the results further, since this is not an issue for the .Net API.
