### ISSUE TITLE
 Could not load file or assembly 'Hl7.Fhir.R4.Core' Plugin error

### ISSUE THREAD

**Issue by murali2805** [FirelyTeam/fhir-net-api#1394]
I was trying to generate a FHIR JSON from a plugin for Dynamics (.Net Framework Class library). I see the below error when the plugin is triggered.

````Unhandled exception:
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): FollowupPlugin.FollowupPlugin: System.IO.FileNotFoundException: Could not load file or assembly 'Hl7.Fhir.R4.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' or one of its dependencies. The system cannot find the file specified.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>d908e678-de19-4dc5-8540-2663a882469a</ActivityId>
<ErrorCode>-2147220956</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink i:nil="true" />
<Message>An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): FollowupPlugin.FollowupPlugin: System.IO.FileNotFoundException: Could not load file or assembly 'Hl7.Fhir.R4.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' or one of its dependencies. The system cannot find the file specified.</Message>
<Timestamp>2020-06-09T08:01:01.2646169Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault i:nil="true" />
<OriginalException>System.IO.FileNotFoundException
at FollowupPlugin.FollowupPlugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass15_0.&lt;Execute&gt;b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage)
at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException>
<TraceText i:nil="true" />
</OrganizationServiceFault>````

**Comment by ewoutkramer** [comment]
The codepaths in this stack trace are from Dynamics (Microsoft.Xrm) . It seems that product does not know where to find our library - as you are already suggesting.

But it is unclear to me what we can do about this?  This seems to be a configuration error in Dynamics - I see no information that suggests we can do anything to fix this, our code is not running yet.
